services:
  wswe-app:
    build: .
    container_name: wswe_app
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:alpine
    container_name: wswe_db
    environment:
      - POSTGRES_DB=wswe_db
      - POSTGRES_USER=wswe_user
      - POSTGRES_PASSWORD=wswe_pass
    ports:
      - "5432:5432"
    restart: always